name: Build iOS IPA (Kivy)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      PROJ_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pkg-config
          brew link libtool
          pip install Cython==3.0.11
          pip install kivy-ios

      - name: Build kivy-ios frameworks
        run: |
          toolchain build python3
          toolchain build kivy

      - name: Create Xcode project
        run: |
          toolchain create xando $PROJ_DIR/main.py
          echo "Created project structure:"
          ls -R $PROJ_DIR/xando-ios

      - name: Build Xcode project
        run: |
          cd $PROJ_DIR/xando-ios
          echo "== Available schemes =="
          xcodebuild -list
          xcodebuild \
            -project xando.xcodeproj \
            -scheme xando \
            -configuration Release \
            -derivedDataPath build



      - name: Package IPA (no signing)
        run: |
          mkdir -p $PROJ_DIR/output
          xcrun -sdk iphoneos PackageApplication \
            -v $PROJ_DIR/xando-ios/build/Build/Products/Release-iphoneos/xando.app \
            -o $PROJ_DIR/output/xando.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: "xando-ipa"
          path: ${{ github.workspace }}/output/xando.ipa
          if-no-files-found: error
