name: Build iOS IPA (Kivy)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      PROJ_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build IPA (Homebrew)
        run: |
          brew install autoconf automake libtool pkg-config
          brew link libtool
          pip install Cython==3.0.11
          pip install kivy-ios
          toolchain build kivy
          toolchain create "XandO" $PROJ_DIR
          echo "Workspace is $PROJ_DIR"
          ls -R $PROJ_DIR

      - name: Upload Xcode Project artifact
        uses: actions/upload-artifact@v4
        with:
          name: xando-xcodeproj
          path: ${{ env.PROJ_DIR }}/xando-ios
          if-no-files-found: error

